platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'Firebase/RemoteConfig', '8.14.0'
  pod 'Firebase/Messaging', '8.14.0'
  pod 'Firebase/Analytics', '8.14.0'
  pod 'Firebase/DynamicLinks', '8.14.0'
  pod 'Firebase/Crashlytics', '8.14.0'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end