platform :ios, '11.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'Firebase/Core', '6.1.0'
  pod 'Firebase/RemoteConfig', '6.1.0'
  pod 'Firebase/Messaging', '6.1.0'
  pod 'Firebase/Analytics', '6.1.0'
  pod 'Firebase/DynamicLinks', '6.1.0'
  # Crashlytics config for Firebase
  pod 'Fabric', '1.10.2'
  pod 'Crashlytics', '3.14.0'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end