platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'Firebase/Core', '6.1.0'
  pod 'Firebase/RemoteConfig', '6.1.0'
  pod 'Firebase/Messaging', '6.1.0'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end